version: 2.1
orbs:
  node: circleci/node@2.1.0
jobs:
  all:
    docker:
      - image: cypress/base:12
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn format:check --all
      - run: yarn affected:lint --all
      - run: yarn affected:test --all
      - run:
          command: yarn affected:e2e --all
          no_output_timeout: 20m
workflows:
  default:
    jobs:
      - all
